### ISSUE TITLE
"BINGO!"

### ISSUE THREAD

**Issue by AndersLowenborg** [marcusoftnet/booooring.com#1]
We need it...

**Comment by marcusoftnet** [comment]
I'll see what I can do :package:

**Comment by marcusoftnet** [comment]
It's now fixed

**Comment by AndersLowenborg** [comment]
Yes!!!
Den 12 feb 2015 04:22 skrev "Marcus Hammarberg" notifications@github.com:

**Comment by marcusoftnet** [comment]
http://booooring.com/sound/yesssss?autoplay=true
